"""Add new profile fields for body analysis

Revision ID: 747835c67569
Revises: b6228141e5fe
Create Date: 2025-12-02 01:59:15.651599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '747835c67569'
down_revision = 'b6228141e5fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_created_at'))

    op.drop_table('chat_message')
    op.drop_table('recipe')
    op.drop_table('knowledge_base')
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('work_activity_level', sa.String(length=20), nullable=True))
        batch_op.drop_column('goal')
        batch_op.drop_column('exercise_preference')
        batch_op.drop_column('work_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_level', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('exercise_preference', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('goal', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('work_activity_level')
        batch_op.drop_column('exercise_level')

    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.TEXT(), nullable=True))

    op.create_table('knowledge_base',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=512), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('ingredients', sa.TEXT(), nullable=True),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.Column('prep_time', sa.INTEGER(), nullable=True),
    sa.Column('cook_time', sa.INTEGER(), nullable=True),
    sa.Column('servings', sa.INTEGER(), nullable=True),
    sa.Column('calories', sa.FLOAT(), nullable=True),
    sa.Column('protein_g', sa.FLOAT(), nullable=True),
    sa.Column('carbs_g', sa.FLOAT(), nullable=True),
    sa.Column('fat_g', sa.FLOAT(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=True),
    sa.Column('is_from_user', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('context_docs', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
