"""Initial migration

Revision ID: b6228141e5fe
Revises: 
Create Date: 2025-11-12 12:41:39.567353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6228141e5fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_log', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
